[16:18:46] System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Service.ServiceProvider.Provider.GetAsync[TResult](String uri, String token) in D:\StoreProduct.MVC\StoreProduct.WebMVC\Service\ServiceProvider\Provider.cs:line 43
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

[16:23:16] System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Service.ServiceProvider.Provider.GetAsync[TResult](String uri, String token) in D:\StoreProduct.MVC\StoreProduct.WebMVC\Service\ServiceProvider\Provider.cs:line 43
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

